-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Drop existing tables to recreate (order matters because of foreign keys)
drop table if exists public.chat_messages cascade;
drop table if exists public.swap_proposals cascade;
drop table if exists public.swap_requests cascade;
drop table if exists public.flight_duties cascade;
drop table if exists public.profiles cascade;

-- 1. PROFILES TABLE
create table public.profiles (
    id text primary key,
    email text unique not null,
    name text not null,
    username text,
    rank text not null check (rank in ('captain', 'first_officer')),
    base text not null default 'BEY',
    qualifications text[] not null default '{}'::text[]
);

-- Enable RLS
alter table public.profiles enable row level security;
create policy "Allow public read access to profiles" on public.profiles for select using (true);
create policy "Allow all write access to profiles" on public.profiles for all using (true) with check (true);

-- 2. FLIGHT DUTIES TABLE
create table public.flight_duties (
    id text primary key,
    pilot_id text references public.profiles(id) on delete cascade,
    duty_type text not null check (duty_type in ('flight', 'standby', 'simulator', 'off', 'training')),
    flight_number text,
    origin text,
    destination text,
    departure_time timestamptz,
    arrival_time timestamptz,
    reporting_time timestamptz,
    release_time timestamptz,
    block_time_mins integer,
    aircraft_type text,
    day_number integer not null
);

alter table public.flight_duties enable row level security;
create policy "Allow public read access to flight_duties" on public.flight_duties for select using (true);
create policy "Allow all write access to flight_duties" on public.flight_duties for all using (true) with check (true);

-- 3. SWAP REQUESTS TABLE
create table public.swap_requests (
    id text primary key,
    pilot_id text references public.profiles(id) on delete cascade,
    flight_id text references public.flight_duties(id) on delete cascade,
    preferred_destination text not null,
    preferred_date_range_start text not null,
    preferred_date_range_end text not null,
    notes text,
    status text not null check (status in ('open', 'matched', 'cancelled')),
    created_at timestamptz default now()
);

alter table public.swap_requests enable row level security;
create policy "Allow public read access to swap_requests" on public.swap_requests for select using (true);
create policy "Allow all write access to swap_requests" on public.swap_requests for all using (true) with check (true);

-- 4. SWAP PROPOSALS TABLE
create table public.swap_proposals (
    id text primary key,
    request_id text references public.swap_requests(id) on delete cascade,
    proposer_id text references public.profiles(id) on delete cascade,
    proposed_flight_id text references public.flight_duties(id) on delete cascade,
    status text not null check (status in ('pending', 'accepted', 'rejected')),
    legality_check_passed boolean not null default true,
    legality_notes text,
    created_at timestamptz default now()
);

alter table public.swap_proposals enable row level security;
create policy "Allow public read access to swap_proposals" on public.swap_proposals for select using (true);
create policy "Allow all write access to swap_proposals" on public.swap_proposals for all using (true) with check (true);

-- 5. CHAT MESSAGES TABLE
create table public.chat_messages (
    id text primary key,
    room_id text not null,
    sender_id text references public.profiles(id) on delete cascade,
    content text not null,
    created_at timestamptz default now()
);

alter table public.chat_messages enable row level security;
create policy "Allow public read access to chat_messages" on public.chat_messages for select using (true);
create policy "Allow all write access to chat_messages" on public.chat_messages for all using (true) with check (true);

-- ==========================================
-- SEED DATA
-- ==========================================

-- Insert profiles
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('naim-id', 'n.moghabghab@mea.com.lb', 'MOGHABGHAB, NAIM ghassan', 'n.moghabghab', 'first_officer', 'BEY', ARRAY['A320', 'A321', 'A32A']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('rayan-id', 'r.mroueh@mea.com.lb', 'MROUEH, RAYAN jamal', 'r.mroueh', 'first_officer', 'BEY', ARRAY['A320', 'A321', 'A32A']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('shibli-id', 's.awanni@mea.com.lb', 'AWANNI, SHIBLI ri', 's.awanni', 'first_officer', 'BEY', ARRAY['A321']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('rami-id', 'r.abboud@mea.com.lb', 'ABBOUD, RAMI hassan', 'r.abboud', 'first_officer', 'BEY', ARRAY['A321']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('jamil-id', 'j.abdulmalak@mea.com.lb', 'ABDUL MALAK, JAMIL mah', 'j.abdulmalak', 'first_officer', 'BEY', ARRAY['A330']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('khaled-id', 'k.abijomaa@mea.com.lb', 'ABI JOMAA, KHALED hoss', 'k.abijomaa', 'first_officer', 'BEY', ARRAY['A320']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('richard-id', 'r.abitorbey@mea.com.lb', 'ABI TOBBY, RICHARD an', 'r.abitorbey', 'first_officer', 'BEY', ARRAY['A330']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('paul-id', 'p.aboueiwan@mea.com.lb', 'ABOU EIWAN, PAUL edmon', 'p.aboueiwan', 'first_officer', 'BEY', ARRAY['A330']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('ziad-id', 'z.abourjily@mea.com.lb', 'ABOU RJILY, ZIAD wali', 'z.abourjily', 'first_officer', 'BEY', ARRAY['A321']);
insert into public.profiles (id, email, name, username, rank, base, qualifications) values ('julio-id', 'j.abousaleh@mea.com.lb', 'ABOU SALEH, JULIO mich', 'j.abousaleh', 'first_officer', 'BEY', ARRAY['A321']);

-- Insert flight duties
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-1', 'naim-id', 'flight', 'ME201', 'BEY', 'LHR', '2026-05-01T05:11:00Z', '2026-05-01T10:09:00Z', '2026-05-01T04:11:00Z', '2026-05-01T10:39:00Z', 298, 'A321', 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-2', 'naim-id', 'flight', 'ME202', 'LHR', 'BEY', '2026-05-02T12:34:00Z', '2026-05-02T17:24:00Z', '2026-05-02T11:34:00Z', '2026-05-02T17:54:00Z', 290, 'A321', 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-3', 'naim-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-4', 'naim-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-5-1', 'naim-id', 'training', 'SIM-1', 'BEY', 'BEY', '2026-05-05T04:28:00Z', '2026-05-05T06:29:00Z', '2026-05-05T04:28:00Z', '2026-05-05T06:29:00Z', 121, 'A320', 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-6', 'naim-id', 'standby', NULL, 'BEY', NULL, '2026-05-06T12:01:00Z', '2026-05-06T23:59:00Z', '2026-05-06T12:01:00Z', '2026-05-06T23:59:00Z', 718, NULL, 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-15-1', 'naim-id', 'flight', 'ME310', 'BEY', 'AMM', '2026-05-15T04:30:00Z', '2026-05-15T05:24:00Z', '2026-05-15T03:30:00Z', '2026-05-15T05:54:00Z', 54, 'A320', 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-15-2', 'naim-id', 'flight', 'ME311', 'AMM', 'BEY', '2026-05-15T06:19:00Z', '2026-05-15T07:15:00Z', '2026-05-15T05:49:00Z', '2026-05-15T07:45:00Z', 56, 'A320', 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-15-3', 'naim-id', 'flight', 'ME320', 'BEY', 'BGW', '2026-05-15T08:50:00Z', '2026-05-15T10:22:00Z', '2026-05-15T07:50:00Z', '2026-05-15T10:52:00Z', 92, 'A320', 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-naim-15-4', 'naim-id', 'flight', 'ME321', 'BGW', 'BEY', '2026-05-15T11:09:00Z', '2026-05-15T12:57:00Z', '2026-05-15T10:39:00Z', '2026-05-15T13:27:00Z', 108, 'A320', 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rayan-5-1', 'rayan-id', 'flight', 'ME418', 'BEY', 'AUH', '2026-05-05T12:35:00Z', '2026-05-05T16:00:00Z', '2026-05-05T11:35:00Z', '2026-05-05T16:30:00Z', 205, 'A321', 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rayan-5-2', 'rayan-id', 'flight', 'ME419', 'AUH', 'BEY', '2026-05-05T16:55:00Z', '2026-05-05T21:10:00Z', '2026-05-05T16:25:00Z', '2026-05-05T21:40:00Z', 255, 'A321', 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rayan-10-1', 'rayan-id', 'flight', 'ME201', 'BEY', 'LHR', '2026-05-10T05:10:00Z', '2026-05-10T10:15:00Z', '2026-05-10T04:10:00Z', '2026-05-10T10:45:00Z', 305, 'A321', 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rayan-10-2', 'rayan-id', 'flight', 'ME202', 'LHR', 'BEY', '2026-05-10T12:00:00Z', '2026-05-10T16:35:00Z', '2026-05-10T11:00:00Z', '2026-05-10T17:05:00Z', 275, 'A321', 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-1', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-2', 'shibli-id', 'flight', 'ME422', 'BEY', 'DXB', NULL, NULL, '2026-05-02T11:00:00Z', '2026-05-02T18:00:00Z', 220, 'A321', 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-3', 'shibli-id', 'flight', 'ME436', 'BEY', 'DOH', NULL, NULL, '2026-05-03T12:00:00Z', '2026-05-03T19:00:00Z', 180, 'A321', 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-4', 'shibli-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-04T12:01:00Z', '2026-05-04T23:59:00Z', NULL, NULL, 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-5', 'shibli-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-05T12:01:00Z', '2026-05-05T23:59:00Z', NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-6', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-7', 'shibli-id', 'flight', 'ME322', 'BEY', 'CAI', NULL, NULL, '2026-05-07T08:00:00Z', '2026-05-07T14:00:00Z', 90, 'A321', 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-8', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-9', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-10', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-11', 'shibli-id', 'flight', 'ME312', 'BEY', 'LHR', NULL, NULL, '2026-05-11T12:00:00Z', '2026-05-11T18:00:00Z', 300, 'A321', 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-12', 'shibli-id', 'flight', 'ME322', 'BEY', 'DXB', NULL, NULL, '2026-05-12T11:00:00Z', '2026-05-12T18:00:00Z', 220, 'A321', 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-13', 'shibli-id', 'flight', 'ME434', 'BEY', 'DOH', NULL, NULL, '2026-05-13T10:00:00Z', '2026-05-13T17:00:00Z', 180, 'A321', 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-14', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-15', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-16', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-17', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-18', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-19', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-20', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-21', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-22', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-23', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-24', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-25', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-26', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-27', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-28', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-29', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-30', 'shibli-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-shibli-id-31', 'shibli-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-1', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-2', 'rami-id', 'flight', 'ME251', 'BEY', 'ATH', NULL, NULL, '2026-05-02T10:00:00Z', '2026-05-02T15:00:00Z', 120, 'A321', 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-3', 'rami-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-03T00:01:00Z', '2026-05-03T12:00:00Z', NULL, NULL, 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-4', 'rami-id', 'flight', 'ME364', 'BEY', 'AMM', NULL, NULL, '2026-05-04T07:00:00Z', '2026-05-04T11:00:00Z', 60, 'A321', 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-5', 'rami-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-05T00:01:00Z', '2026-05-05T12:00:00Z', NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-6', 'rami-id', 'flight', 'ME426', 'BEY', 'DXB', NULL, NULL, '2026-05-06T15:00:00Z', '2026-05-06T22:00:00Z', 220, 'A321', 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-7', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-8', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-9', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-10', 'rami-id', 'flight', 'ME426', 'BEY', 'DXB', NULL, NULL, '2026-05-10T15:00:00Z', '2026-05-10T22:00:00Z', 220, 'A321', 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-11', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-12', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-13', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-14', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-15', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-16', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-17', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-18', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-19', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-20', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-21', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-22', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-23', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-24', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-25', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-26', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-27', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-28', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-29', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-30', 'rami-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-rami-id-31', 'rami-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-1', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-2', 'jamil-id', 'flight', 'ME324', 'BEY', 'CAI', NULL, NULL, '2026-05-02T09:00:00Z', '2026-05-02T15:00:00Z', 90, 'A330', 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-3', 'jamil-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-03T12:01:00Z', '2026-05-03T23:59:00Z', NULL, NULL, 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-4', 'jamil-id', 'flight', 'ME434', 'BEY', 'DOH', NULL, NULL, '2026-05-04T10:00:00Z', '2026-05-04T17:00:00Z', 180, 'A330', 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-5', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-6', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-7', 'jamil-id', 'flight', 'ME422', 'BEY', 'DXB', NULL, NULL, '2026-05-07T11:00:00Z', '2026-05-07T18:00:00Z', 220, 'A330', 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-8', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-9', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-10', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-11', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-12', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-13', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-14', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-15', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-16', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-17', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-18', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-19', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-20', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-21', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-22', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-23', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-24', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-25', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-26', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-27', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-28', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-29', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-30', 'jamil-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-jamil-id-31', 'jamil-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-1', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-2', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-3', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-4', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-5', 'khaled-id', 'training', 'CEO11', NULL, NULL, NULL, NULL, '2026-05-05T08:00:00Z', '2026-05-05T16:00:00Z', NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-6', 'khaled-id', 'flight', 'ME426', 'BEY', 'DXB', NULL, NULL, NULL, NULL, 220, 'A320', 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-7', 'khaled-id', 'flight', 'ME326', 'BEY', 'CAI', NULL, NULL, NULL, NULL, 90, 'A320', 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-8', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-9', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-10', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-11', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-12', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-13', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-14', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-15', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-16', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-17', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-18', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-19', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-20', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-21', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-22', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-23', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-24', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-25', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-26', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-27', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-28', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-29', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-30', 'khaled-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-khaled-id-31', 'khaled-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-1', 'richard-id', 'flight', 'ME211', 'BEY', 'LHR', NULL, NULL, NULL, NULL, 300, 'A330', 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-2', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-3', 'richard-id', 'flight', 'ME428', 'BEY', 'DXB', NULL, NULL, NULL, NULL, 220, 'A330', 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-4', 'richard-id', 'flight', 'ME322', 'BEY', 'CAI', NULL, NULL, NULL, NULL, 90, 'A330', 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-5', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-6', 'richard-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-06T12:01:00Z', '2026-05-06T23:59:00Z', NULL, NULL, 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-7', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-8', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-9', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-10', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-11', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-12', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-13', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-14', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-15', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-16', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-17', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-18', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-19', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-20', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-21', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-22', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-23', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-24', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-25', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-26', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-27', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-28', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-29', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-30', 'richard-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-richard-id-31', 'richard-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-1', 'paul-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-01T00:01:00Z', '2026-05-01T12:00:00Z', NULL, NULL, 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-2', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-3', 'paul-id', 'flight', 'ME229', 'BEY', 'PAR', NULL, NULL, NULL, NULL, 280, 'A330', 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-4', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-5', 'paul-id', 'flight', 'ME430', 'BEY', 'DXB', NULL, NULL, NULL, NULL, 220, 'A330', 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-6', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-7', 'paul-id', 'flight', 'ME211', 'BEY', 'LHR', NULL, NULL, NULL, NULL, 300, 'A330', 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-8', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-9', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-10', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-11', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-12', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-13', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-14', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-15', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-16', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-17', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-18', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-19', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-20', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-21', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-22', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-23', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-24', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-25', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-26', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-27', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-28', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-29', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-30', 'paul-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-paul-id-31', 'paul-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-1', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-2', 'ziad-id', 'flight', 'ME229', 'BEY', 'PAR', NULL, NULL, NULL, NULL, 280, 'A321', 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-3', 'ziad-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-03T12:01:00Z', '2026-05-03T23:59:00Z', NULL, NULL, 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-4', 'ziad-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-04T12:01:00Z', '2026-05-04T23:59:00Z', NULL, NULL, 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-5', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-6', 'ziad-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-06T00:01:00Z', '2026-05-06T12:00:00Z', NULL, NULL, 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-7', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-8', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-9', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-10', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-11', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-12', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-13', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-14', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-15', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-16', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-17', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-18', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-19', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-20', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-21', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-22', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-23', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-24', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-25', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-26', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-27', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-28', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-29', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-30', 'ziad-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-ziad-id-31', 'ziad-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-1', 'julio-id', 'flight', 'ME217', 'BEY', 'FCO', NULL, NULL, NULL, NULL, 200, 'A321', 1);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-2', 'julio-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-02T02:00:00Z', '2026-05-02T14:00:00Z', NULL, NULL, 2);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-3', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-4', 'julio-id', 'flight', 'ME442', 'BEY', 'DOH', NULL, NULL, NULL, NULL, 180, 'A321', 4);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-5', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-6', 'julio-id', 'flight', 'ME247', 'BEY', 'MAD', NULL, NULL, NULL, NULL, 300, 'A321', 6);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-7', 'julio-id', 'standby', NULL, NULL, NULL, NULL, NULL, '2026-05-07T12:01:00Z', '2026-05-07T23:59:00Z', NULL, NULL, 7);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-8', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 8);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-9', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 9);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-10', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-11', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 11);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-12', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 12);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-13', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 13);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-14', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 14);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-15', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 15);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-16', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 16);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-17', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 17);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-18', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 18);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-19', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 19);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-20', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-21', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 21);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-22', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 22);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-23', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-24', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 24);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-25', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 25);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-26', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 26);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-27', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 27);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-28', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 28);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-29', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 29);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-30', 'julio-id', 'off', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 30);
insert into public.flight_duties (id, pilot_id, duty_type, flight_number, origin, destination, departure_time, arrival_time, reporting_time, release_time, block_time_mins, aircraft_type, day_number) values ('f-julio-id-31', 'julio-id', 'flight', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 31);

-- Insert swap requests
insert into public.swap_requests (id, pilot_id, flight_id, preferred_destination, preferred_date_range_start, preferred_date_range_end, notes, status, created_at) values ('req-rayan-1', 'rayan-id', 'f-rayan-10-1', 'Gulf (DXB/AUH) or Off Days', '2026-05-10', '2026-05-12', 'Need to swap LHR on the 10th. Prefer a regional sector or weekend off if possible.', 'open', '2026-05-20T10:00:00Z');
